-- +goose Up
-- +goose StatementBegin

-- app_user mirrors upstream's user_data: every authenticated principal
-- that interacts with the API has a row here. Created on first sight
-- (post-login) by the API; subsequent logins update the cached display
-- fields.
CREATE TABLE app_user (
    user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub         TEXT NOT NULL UNIQUE,
    username    TEXT NOT NULL,
    display_name TEXT NOT NULL DEFAULT '',
    email       TEXT NOT NULL DEFAULT '',
    last_claims JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_app_user_username ON app_user (lower(username));

-- collection is the top-level container for assets, STIG assignments,
-- grants and reviews. Settings and metadata are JSONB so we can map
-- upstream's nested CollectionSettings and free-form Metadata schemas
-- without rigid columns; the API marshals them via the OpenAPI types.
CREATE TABLE collection (
    collection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(45) NOT NULL,
    description   VARCHAR(255),
    settings      JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata      JSONB NOT NULL DEFAULT '{}'::jsonb,
    state         VARCHAR(16) NOT NULL DEFAULT 'enabled'
                  CHECK (state IN ('enabled', 'disabled', 'cloning')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Upstream enforces a case-insensitive uniqueness on enabled-collection
-- names. Partial unique index keeps soft-deleted/disabled collections
-- from blocking the namespace.
CREATE UNIQUE INDEX idx_collection_name_unique
    ON collection (lower(name))
    WHERE state = 'enabled';

-- collection_grant maps users to collections with a role. Upstream
-- role_id values: 1=restricted, 2=full, 3=manage, 4=owner.
CREATE TABLE collection_grant (
    grant_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id  BIGINT NOT NULL REFERENCES collection(collection_id) ON DELETE CASCADE,
    user_id        BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    role_id        SMALLINT NOT NULL CHECK (role_id BETWEEN 1 AND 4),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (collection_id, user_id)
);

CREATE INDEX idx_collection_grant_user ON collection_grant (user_id);

-- updated_at maintenance trigger shared by tables with an updated_at
-- column. Defined in a single place so future migrations can opt in.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_app_user_updated_at
    BEFORE UPDATE ON app_user
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_collection_updated_at
    BEFORE UPDATE ON collection
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS trg_collection_updated_at ON collection;
DROP TRIGGER IF EXISTS trg_app_user_updated_at ON app_user;
DROP FUNCTION IF EXISTS set_updated_at();
DROP TABLE IF EXISTS collection_grant;
DROP TABLE IF EXISTS collection;
DROP TABLE IF EXISTS app_user;
-- +goose StatementEnd
