-- +goose Up
-- +goose StatementBegin

CREATE TABLE stig (
    benchmark_id  VARCHAR(255) PRIMARY KEY,
    title         VARCHAR(255) NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_stig_updated_at
    BEFORE UPDATE ON stig
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE stig_revision (
    revision_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    benchmark_id   VARCHAR(255) NOT NULL REFERENCES stig(benchmark_id) ON DELETE CASCADE,
    revision_str   VARCHAR(45) NOT NULL,
    version        VARCHAR(45) NOT NULL DEFAULT '',
    release        VARCHAR(45) NOT NULL DEFAULT '',
    release_date   DATE,
    status         VARCHAR(45) NOT NULL DEFAULT '',
    status_date    DATE,
    benchmark_date DATE,
    description    TEXT NOT NULL DEFAULT '',
    source         TEXT NOT NULL DEFAULT '',
    marking        TEXT,
    imported_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (benchmark_id, revision_str)
);

CREATE INDEX idx_stig_revision_benchmark ON stig_revision (benchmark_id);

CREATE TABLE stig_rule (
    rule_pk        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id    BIGINT NOT NULL REFERENCES stig_revision(revision_id) ON DELETE CASCADE,
    rule_id        VARCHAR(45) NOT NULL,
    version_str    VARCHAR(45) NOT NULL DEFAULT '',
    group_id       VARCHAR(45) NOT NULL DEFAULT '',
    group_title    TEXT NOT NULL DEFAULT '',
    severity       VARCHAR(16) NOT NULL DEFAULT 'medium'
                   CHECK (severity IN ('low', 'medium', 'high', 'unknown')),
    weight         VARCHAR(16) NOT NULL DEFAULT '',
    title          TEXT NOT NULL DEFAULT '',
    description    TEXT NOT NULL DEFAULT '',
    check_system   VARCHAR(255) NOT NULL DEFAULT '',
    check_content  TEXT NOT NULL DEFAULT '',
    fix_id         VARCHAR(45) NOT NULL DEFAULT '',
    fix_text       TEXT NOT NULL DEFAULT '',
    UNIQUE (revision_id, rule_id)
);

CREATE INDEX idx_stig_rule_rule_id ON stig_rule (rule_id);

CREATE TABLE cci (
    cci          VARCHAR(16) PRIMARY KEY,
    definition   TEXT NOT NULL DEFAULT '',
    type         VARCHAR(20) NOT NULL DEFAULT '',
    status       VARCHAR(20) NOT NULL DEFAULT '',
    publish_date DATE
);

CREATE TABLE stig_rule_cci (
    rule_pk      BIGINT NOT NULL REFERENCES stig_rule(rule_pk) ON DELETE CASCADE,
    cci          VARCHAR(16) NOT NULL REFERENCES cci(cci) ON DELETE CASCADE,
    PRIMARY KEY (rule_pk, cci)
);

CREATE INDEX idx_stig_rule_cci_cci ON stig_rule_cci (cci);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP TABLE IF EXISTS stig_rule_cci;
DROP TABLE IF EXISTS cci;
DROP TABLE IF EXISTS stig_rule;
DROP TABLE IF EXISTS stig_revision;
DROP TRIGGER IF EXISTS trg_stig_updated_at ON stig;
DROP TABLE IF EXISTS stig;

-- +goose StatementEnd
