-- +goose Up
-- +goose StatementBegin

-- asset is a host / device tracked inside a Collection. Mirrors
-- upstream's `asset` table: one row per evaluable target, with
-- optional fqdn/ip/mac and a free-form metadata jsonb blob that the
-- API marshals via the OpenAPI Metadata schema.
CREATE TABLE asset (
    asset_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id BIGINT NOT NULL REFERENCES collection(collection_id) ON DELETE CASCADE,
    name          VARCHAR(255) NOT NULL,
    fqdn          VARCHAR(255),
    ip            VARCHAR(255),
    mac           VARCHAR(255),
    description   VARCHAR(255),
    noncomputing  BOOLEAN NOT NULL DEFAULT false,
    metadata      JSONB NOT NULL DEFAULT '{}'::jsonb,
    state         VARCHAR(16) NOT NULL DEFAULT 'enabled'
                  CHECK (state IN ('enabled', 'disabled')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Upstream enforces case-insensitive name uniqueness within a Collection
-- for enabled assets only; disabled rows are kept for audit history.
CREATE UNIQUE INDEX idx_asset_name_per_collection
    ON asset (collection_id, lower(name))
    WHERE state = 'enabled';

CREATE INDEX idx_asset_collection ON asset (collection_id) WHERE state = 'enabled';

CREATE TRIGGER trg_asset_updated_at
    BEFORE UPDATE ON asset
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- asset_stig: which benchmarks are mapped to an asset. A NULL
-- revision_id means "use the latest revision available in stig_revision"
-- (matching upstream's notion of a default revision). A row pinned to a
-- specific revision_id keeps Reviews stable across upstream STIG
-- updates.
CREATE TABLE asset_stig (
    asset_id      BIGINT NOT NULL REFERENCES asset(asset_id) ON DELETE CASCADE,
    benchmark_id  VARCHAR(255) NOT NULL REFERENCES stig(benchmark_id) ON DELETE CASCADE,
    revision_id   BIGINT REFERENCES stig_revision(revision_id) ON DELETE SET NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (asset_id, benchmark_id)
);

CREATE INDEX idx_asset_stig_benchmark ON asset_stig (benchmark_id);

-- Labels are per-Collection tags for asset grouping. UUIDs because the
-- OpenAPI spec exposes label_id as a string-uuid and upstream uses
-- mysql binary(16). gen_random_uuid() is built into Postgres 13+.
CREATE TABLE collection_label (
    label_id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    collection_id BIGINT NOT NULL REFERENCES collection(collection_id) ON DELETE CASCADE,
    name          VARCHAR(255) NOT NULL,
    color         VARCHAR(8) NOT NULL,
    description   VARCHAR(255),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_collection_label_name
    ON collection_label (collection_id, lower(name));

CREATE TRIGGER trg_collection_label_updated_at
    BEFORE UPDATE ON collection_label
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Many-to-many: each label is applied to zero or more assets within
-- the same Collection. The (label_id, asset_id) PK prevents dupes;
-- application code enforces that label and asset share a collection.
CREATE TABLE collection_label_asset (
    label_id  UUID NOT NULL REFERENCES collection_label(label_id) ON DELETE CASCADE,
    asset_id  BIGINT NOT NULL REFERENCES asset(asset_id) ON DELETE CASCADE,
    PRIMARY KEY (label_id, asset_id)
);

CREATE INDEX idx_collection_label_asset_asset ON collection_label_asset (asset_id);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS collection_label_asset;
DROP TABLE IF EXISTS collection_label;
DROP TABLE IF EXISTS asset_stig;
DROP TRIGGER IF EXISTS trg_asset_updated_at ON asset;
DROP TABLE IF EXISTS asset;
-- +goose StatementEnd
