-- +goose Up
-- +goose StatementBegin

-- review is a single evaluator decision (pass/fail/notapplicable/…)
-- on one (Asset × Rule) pair. The (asset_id, rule_id) pair is unique;
-- the active row is updated in-place and the previous content is
-- copied into review_history before the update.
--
-- The schema mirrors upstream's `review` table but folds the
-- status sub-record onto the same row (status_label, status_text,
-- status_user_id, status_ts) since Postgres has no problem with NULL
-- side fields. ResultEngine arrives as an optional JSON blob and is
-- stored verbatim.
CREATE TABLE review (
    review_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id       BIGINT NOT NULL REFERENCES asset(asset_id) ON DELETE CASCADE,
    rule_id        VARCHAR(45) NOT NULL,
    result         VARCHAR(16) NOT NULL
                   CHECK (result IN ('pass','fail','notapplicable','notchecked','informational','unknown','error','notselected','fixed')),
    detail         TEXT NOT NULL DEFAULT '',
    comment        TEXT NOT NULL DEFAULT '',
    auto_result    BOOLEAN NOT NULL DEFAULT false,
    result_engine  JSONB,
    metadata       JSONB NOT NULL DEFAULT '{}'::jsonb,
    status_label   VARCHAR(16) NOT NULL DEFAULT 'saved'
                   CHECK (status_label IN ('saved','submitted','accepted','rejected')),
    status_text    VARCHAR(511),
    status_user_id BIGINT REFERENCES app_user(user_id) ON DELETE SET NULL,
    status_ts      TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id        BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE RESTRICT,
    ts             TIMESTAMPTZ NOT NULL DEFAULT now(),
    touch_ts       TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_review_asset_rule
    ON review (asset_id, rule_id);

CREATE INDEX idx_review_rule ON review (rule_id);
CREATE INDEX idx_review_user ON review (user_id);
CREATE INDEX idx_review_status ON review (status_label);

CREATE TRIGGER trg_review_updated_at
    BEFORE UPDATE ON review
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- review_history captures every previous version of a review's
-- content. A row is appended on every PUT/PATCH that changes a
-- semantic field, and on DELETE. Upstream models this the same way.
-- review_id is NULLABLE so a deleted-then-recreated review's history
-- isn't dropped when the original row's ON DELETE CASCADE fires.
CREATE TABLE review_history (
    history_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id      BIGINT REFERENCES review(review_id) ON DELETE SET NULL,
    asset_id       BIGINT NOT NULL,
    rule_id        VARCHAR(45) NOT NULL,
    result         VARCHAR(16) NOT NULL,
    detail         TEXT NOT NULL DEFAULT '',
    comment        TEXT NOT NULL DEFAULT '',
    auto_result    BOOLEAN NOT NULL DEFAULT false,
    result_engine  JSONB,
    status_label   VARCHAR(16) NOT NULL,
    status_text    VARCHAR(511),
    user_id        BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE RESTRICT,
    ts             TIMESTAMPTZ NOT NULL,
    touch_ts       TIMESTAMPTZ NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_review_history_asset_rule
    ON review_history (asset_id, rule_id, created_at DESC);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS review_history;
DROP TRIGGER IF EXISTS trg_review_updated_at ON review;
DROP TABLE IF EXISTS review;
-- +goose StatementEnd
