-- +goose Up
-- +goose StatementBegin

-- Extend app_user with the columns the OpenAPI User schema surfaces.
-- status: available | unavailable (matches UserStatus enum).
-- status_date / status_user_id: when/who last toggled status.
-- privilege_admin: equivalent of upstream's "admin" privilege.
-- privilege_create_collection: equivalent of upstream's "create_collection".
-- sub becomes nullable because admin-pre-created users have no OIDC
-- subject until they first authenticate; on first login the Upsert
-- path stitches the row by username (subject linked then).
ALTER TABLE app_user
    ALTER COLUMN sub DROP NOT NULL,
    ADD COLUMN status            VARCHAR(16) NOT NULL DEFAULT 'available'
                                 CHECK (status IN ('available', 'unavailable')),
    ADD COLUMN status_date       TIMESTAMPTZ,
    ADD COLUMN status_user_id    BIGINT REFERENCES app_user(user_id) ON DELETE SET NULL,
    ADD COLUMN privilege_admin   BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN privilege_create_collection BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN last_access_unix  BIGINT;

-- user_group is the opaque container the UserGroup* OpenAPI shapes
-- reference. Membership lives in user_group_user; collection grants
-- targeted at a group live in collection_grant via the user_group_id
-- column added below.
CREATE TABLE user_group (
    user_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(45) NOT NULL,
    description   VARCHAR(255),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Case-insensitive uniqueness on user group names — upstream behaviour.
CREATE UNIQUE INDEX idx_user_group_name_unique ON user_group (lower(name));

CREATE TRIGGER trg_user_group_updated_at
    BEFORE UPDATE ON user_group
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Many-to-many membership join.
CREATE TABLE user_group_user (
    user_group_id BIGINT NOT NULL REFERENCES user_group(user_group_id) ON DELETE CASCADE,
    user_id       BIGINT NOT NULL REFERENCES app_user(user_id)       ON DELETE CASCADE,
    PRIMARY KEY (user_group_id, user_id)
);

CREATE INDEX idx_user_group_user_user ON user_group_user (user_id);

-- collection_grant gains a user_group_id alternative to user_id so
-- group-level grants survive group membership churn. user_id becomes
-- nullable; the original UNIQUE(collection_id, user_id) constraint
-- still applies but Postgres treats NULL as distinct so multiple
-- group grants on the same collection are allowed. A separate partial
-- unique index covers the group case.
ALTER TABLE collection_grant
    ADD COLUMN user_group_id BIGINT REFERENCES user_group(user_group_id) ON DELETE CASCADE,
    ALTER COLUMN user_id DROP NOT NULL;

CREATE UNIQUE INDEX idx_collection_grant_user_group_unique
    ON collection_grant (collection_id, user_group_id)
    WHERE user_group_id IS NOT NULL;

ALTER TABLE collection_grant
    ADD CONSTRAINT collection_grant_one_grantee
    CHECK ((user_id IS NOT NULL AND user_group_id IS NULL)
        OR (user_id IS NULL AND user_group_id IS NOT NULL));

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

ALTER TABLE collection_grant DROP CONSTRAINT IF EXISTS collection_grant_one_grantee;
DROP INDEX IF EXISTS idx_collection_grant_user_group_unique;
ALTER TABLE collection_grant
    ALTER COLUMN user_id SET NOT NULL,
    DROP COLUMN user_group_id;

DROP TRIGGER IF EXISTS trg_user_group_updated_at ON user_group;
DROP INDEX IF EXISTS idx_user_group_user_user;
DROP TABLE IF EXISTS user_group_user;
DROP INDEX IF EXISTS idx_user_group_name_unique;
DROP TABLE IF EXISTS user_group;

ALTER TABLE app_user
    DROP COLUMN last_access_unix,
    DROP COLUMN privilege_create_collection,
    DROP COLUMN privilege_admin,
    DROP COLUMN status_user_id,
    DROP COLUMN status_date,
    DROP COLUMN status;

-- +goose StatementEnd
