-- +goose Up
-- +goose StatementBegin

-- job_task is the registry of executable units a job can perform.
-- Rows are seeded by the API on startup from the in-process task
-- registry; the seed is idempotent (INSERT … ON CONFLICT DO UPDATE).
-- The command column is informational only — actual execution is
-- driven by the registry, not the row.
CREATE TABLE job_task (
    task_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(45) NOT NULL,
    description VARCHAR(255),
    command     VARCHAR(255),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_job_task_name_unique ON job_task (lower(name));

CREATE TRIGGER trg_job_task_updated_at
    BEFORE UPDATE ON job_task
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- job is a named schedulable unit. event_type is one of:
--   * NULL — manual / on-demand only
--   * 'once' — fires once at event_starts
--   * 'recurring' — fires every event_interval_value event_interval_field
--     starting at event_starts, optionally bounded by event_ends.
-- event_id is upstream's stable string handle for the event slot; we
-- generate one on insert via the generated column for simplicity.
CREATE TABLE job (
    job_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   VARCHAR(45) NOT NULL,
    description            VARCHAR(255),
    event_type             VARCHAR(16)
                              CHECK (event_type IS NULL OR event_type IN ('once', 'recurring')),
    event_id               VARCHAR(45),
    event_enabled          BOOLEAN NOT NULL DEFAULT TRUE,
    event_starts           TIMESTAMPTZ,
    event_ends             TIMESTAMPTZ,
    event_interval_field   VARCHAR(16)
                              CHECK (event_interval_field IS NULL OR event_interval_field IN ('minute', 'hour', 'day', 'week', 'month')),
    event_interval_value   VARCHAR(45),
    created_by_user_id     BIGINT REFERENCES app_user(user_id) ON DELETE SET NULL,
    updated_by_user_id     BIGINT REFERENCES app_user(user_id) ON DELETE SET NULL,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_job_updated_at
    BEFORE UPDATE ON job
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Many-to-many ordered link between jobs and the tasks they run.
-- The seq column preserves the task order requested at create/patch
-- time so RunImmediateJob walks the tasks deterministically.
CREATE TABLE job_task_link (
    job_id  BIGINT NOT NULL REFERENCES job(job_id)      ON DELETE CASCADE,
    task_id BIGINT NOT NULL REFERENCES job_task(task_id) ON DELETE RESTRICT,
    seq     INTEGER NOT NULL,
    PRIMARY KEY (job_id, seq)
);

CREATE INDEX idx_job_task_link_task ON job_task_link (task_id);

-- job_run captures one execution of a job. run_id is a UUIDv4 surfaced
-- to clients (StringUuid in the OpenAPI schema). state ∈ JobRunState
-- ('running' | 'completed' | 'failed'). created tracks the queued/start
-- time; updated bumps every output append + on terminal state.
CREATE TABLE job_run (
    run_id      UUID PRIMARY KEY,
    job_id      BIGINT NOT NULL REFERENCES job(job_id) ON DELETE CASCADE,
    state       VARCHAR(16) NOT NULL DEFAULT 'running'
                  CHECK (state IN ('running', 'completed', 'failed')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_job_run_job ON job_run (job_id, created_at DESC);

CREATE TRIGGER trg_job_run_updated_at
    BEFORE UPDATE ON job_run
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- job_run_output is the append-only stream tailed by GET
-- /jobs/runs/{runId}/output. seq is monotonically increasing within
-- a run; clients pass after-seq to resume tailing.
CREATE TABLE job_run_output (
    run_id  UUID NOT NULL REFERENCES job_run(run_id) ON DELETE CASCADE,
    seq     BIGINT NOT NULL,
    ts      TIMESTAMPTZ NOT NULL DEFAULT now(),
    task_id BIGINT REFERENCES job_task(task_id) ON DELETE SET NULL,
    task    VARCHAR(45) NOT NULL,
    type    VARCHAR(16) NOT NULL DEFAULT 'stdout'
              CHECK (type IN ('stdout', 'stderr', 'system')),
    message TEXT NOT NULL,
    PRIMARY KEY (run_id, seq)
);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP TABLE IF EXISTS job_run_output;
DROP TRIGGER IF EXISTS trg_job_run_updated_at ON job_run;
DROP INDEX IF EXISTS idx_job_run_job;
DROP TABLE IF EXISTS job_run;
DROP INDEX IF EXISTS idx_job_task_link_task;
DROP TABLE IF EXISTS job_task_link;
DROP TRIGGER IF EXISTS trg_job_updated_at ON job;
DROP TABLE IF EXISTS job;
DROP TRIGGER IF EXISTS trg_job_task_updated_at ON job_task;
DROP INDEX IF EXISTS idx_job_task_name_unique;
DROP TABLE IF EXISTS job_task;

-- +goose StatementEnd
