-- +goose Up
-- +goose StatementBegin

-- audit_log captures one row per mutating HTTP request. Reads (GET /
-- HEAD / OPTIONS) are excluded by the middleware so this table stays
-- proportional to write traffic. The payload is the request body
-- with known-sensitive keys redacted; bodies above an operator-tuned
-- size cap are stored as NULL with a `body.truncated=true` marker on
-- the metadata column.
CREATE TABLE audit_log (
    audit_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts          TIMESTAMPTZ NOT NULL DEFAULT now(),
    method      VARCHAR(8)  NOT NULL,
    path        TEXT        NOT NULL,
    route       TEXT,
    status      INTEGER     NOT NULL,
    duration_ms INTEGER     NOT NULL DEFAULT 0,
    user_id     BIGINT      REFERENCES app_user(user_id) ON DELETE SET NULL,
    username    VARCHAR(255),
    subject     VARCHAR(255),
    ip          INET,
    request_id  VARCHAR(64),
    payload     JSONB,
    metadata    JSONB       NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX idx_audit_log_ts ON audit_log (ts DESC);
CREATE INDEX idx_audit_log_user ON audit_log (user_id) WHERE user_id IS NOT NULL;
CREATE INDEX idx_audit_log_path_method ON audit_log (path, method);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS audit_log;
-- +goose StatementEnd
