{{- if not .Values.secrets.existing.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stig-manager.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stig-manager.api.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  databaseUrl: {{ required "secrets.databaseUrl (or secrets.existing.name) is required" .Values.secrets.databaseUrl | quote }}
{{- end }}
